version: '3.2'

services:
  redis:
    container_name: redis
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - "TZ=America/Sao_Paulo"
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root"
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./data:/data/db
