version: '3.2'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./database/redis/data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis

  mongo:
    container_name: mongo
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./database/mongo/data:/data/db
